name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      # Setup NuGet package source
      - name: Setup NuGet package source
        run: dotnet nuget add source https://nuget.pkg.github.com/igjp-sample/index.json
          --name igjp-sample
          --username ${{ secrets.USER }}
          --password ${{ secrets.PAT }}
          --store-password-in-clear-text

      # Add the "Publish SPA for GitHub Pages" package
      - name: Add the "Publish SPA for GitHub Pages" package
        run: dotnet add package PublishSPAforGitHubPages.Build --version 2.1.0

      # Publish the site
      - name: Publish
        run: dotnet publish IgniteUIforBlazorExcelLibraryExample.csproj -c Release -o publish -p GHPages=true

      # Clean up package source
      - name: Clean up package source
        run: dotnet nuget remove source igjp-sample

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true